name: Build and Commit PDF

on:
  push:
    paths:
      - 'main.tex'          
  workflow_dispatch:       

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Set up LaTeX and compile
      uses: dante-ev/latex-action@latest
      with:
        root_file: main.tex

    - name: Move PDF to /pdf/
      run: |
        mkdir -p pdf
        mv main.pdf pdf/main.pdf

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.ACTIONS_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Commit and push PDF
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add pdf/main.pdf
        git commit -m "Автоматическая пересборка PDF" || echo "No changes"
        git push git@github.com:${{ github.repository }}.git HEAD:${{ github.ref_name }}
